### ISSUE TITLE
Only compatible with Swift 4.1 (so OSX High Sierra and XCode 9.3)

### ISSUE THREAD

**Issue by melMass** [jakeheis/Ice#19]
Trying to build using Xcode 9.2 and Swift 4.0 result in the following error as `compactMap` use to be `flatMap`:

```swift
github.com_jakeheis_Ice/Sources/IceKit/Package.swift:106:16: error: value of type '[MatchResult]' has no member 'compactMap'
        return matches.compactMap { $0.captures[0] }
               ^~~~~~~ ~~~~~~~~~~
Failed to build Ice
```

**Comment by jakeheis** [comment]
Swift 4.0 will be supported once #24 is merged in -- I expect to merge it in within the next week!

**Comment by jakeheis** [comment]
`0.7.0` tagged
